import Head from 'next/head'
import Image from 'next/image'
import {
  Card,
  Grid,
  Modal,
  Button,
  CardMedia,
  TextField,
  Typography,
  CardContent,
  CardActions,
  InputAdornment
} from '@mui/material'

import styles from '../styles/modules/Home.module.scss'
import { useState } from 'react'
export default function Home() {
  const [open, setOpen] = useState(false)

  const handleClose = () => {
    setOpen(false)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='hero-banner'>
        <div className='content'>
          {/* <h1>Lorem Ipsum</h1> */}
          {/* <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, dolor dolores! Assumenda
            saepe fugit aliquid excepturi molestiae totam. Ratione, optio, quae a explicabo enim
            laudantium ipsam, quia illo facilis repellendus et nostrum dolores. Praesentium reiciendis
            id officiis mollitia eaque eveniet! Nemo, doloribus! Quidem suscipit.
          </p> */}
          <Button variant="contained" size='large' className='btn'>Contactez-nous</Button>
        </div>
      </section>

      <main className={styles.main}>
        <section className={styles.about}>
          <div className={styles.container}>
            <div className={styles.imageContent}>
              <Image src={'/about.jpg'} width={500} height={500} />
            </div>
            <div className={styles.textContent}>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, dolor dolores! Assumenda
                saepe fugit aliquid excepturi molestiae totam. Ratione, optio, quae a explicabo enim
                laudantium ipsam, quia illo facilis repellendus et nostrum dolores. Praesentium reiciendis
                id officiis mollitia eaque eveniet! Nemo, doloribus! Quidem suscipit.
                id officiis mollitia eaque eveniet! Nemo, doloribus! Quidem suscipit.
                id officiis mollitia eaque eveniet! Nemo, doloribus! Quidem suscipit.
                id officiis mollitia eaque eveniet! Nemo, doloribus! Quidem suscipit.
              </p>
            </div>
          </div>
        </section>

        <section className={styles.donationCategories}>
          <div className={styles.container}>
            <div className={styles.item}>
              <div className={styles.content}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, dolor dolores! Assumenda
                  saepe fugit aliquid excepturi molestiae totam.
                </p>
                <Button variant="contained" onClick={() => setOpen(true)} size='large' className={styles.btn}>Faire un don</Button>
              </div>
            </div>
            <div className={styles.item}>
              <div className={styles.content}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, dolor dolores! Assumenda
                  saepe fugit aliquid excepturi molestiae totam.
                </p>
                <Button variant="contained" onClick={() => setOpen(true)} size='large' className={styles.btn}>Faire un don</Button>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Modal
        open={open}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
        className='containerPaymentModal'
      >
        <Card className='paymentModal'>
          <CardMedia
            sx={{ height: 140 }}
            image="/about.jpg"
            title="green iguana"
          />
          <CardContent>
            <Typography gutterBottom variant="h4" component="div" className={styles.title}>
              Don 1
            </Typography>

            <Grid container spacing={1} alignItems='center' justifyContent='center' >
              <Grid item xs={12}>
                <TextField label="Non" size='small' fullWidth variant="outlined" />
              </Grid>
              <Grid item xs={12}>
                <TextField label="Prenom(s)" size='small' fullWidth variant="outlined" />
              </Grid>
              <Grid item xs={12}>
                <TextField 
                  label="Montant" 
                  size='small' 
                  fullWidth 
                  type='number' 
                  InputProps={{
                    endAdornment: <InputAdornment position="end">FCFA</InputAdornment>,
                  }}
                  variant="outlined" 
                />
              </Grid>
            </Grid>
          </CardContent>
          <CardActions>
            <Button variant="contained" size='large' fullWidth className='btn'>Payez</Button>
          </CardActions>
        </Card>
      </Modal>
    </>
  )
}
