import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/modules/Requirement.module.scss'
import { Button, Modal, Card, CardActions, CardContent, CardMedia, Typography, LinearProgress } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.heroBanner}>
        <div className={styles.content}>
          <h1>Lorem Ipsum</h1>
        </div>
      </section>

      <main className={styles.main}>
        <section className={styles.cardContentGrid}>
          <div className={styles.container} >
            <Card className={styles.needCard}>
              <CardMedia
                sx={{ height: 140 }}
                image="/sable.jpg"
                title="green iguana"
              />
              <CardContent>
                <Typography gutterBottom variant="h4" component="div" className={styles.title}>
                  Sable
                </Typography>
                <div className={styles.goalContent}>
                  <div className={styles.goal}>
                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Objectif:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        100,000,000 FCFA
                      </Typography>
                    </div>

                    <LinearProgress variant="determinate" className={styles.progress} value={10} />

                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Atteint:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        100,000,000 FCFA
                      </Typography>
                    </div>
                  </div>
                </div>
              </CardContent>
              <CardActions>
                <Button variant="contained" size='large' fullWidth className='btn'>Faire un don</Button>
              </CardActions>
            </Card>
            <Card className={styles.needCard}>
              <CardMedia
                sx={{ height: 140 }}
                image="/ciment.jpg"
                title="green iguana"
              />
              <CardContent>
                <Typography gutterBottom variant="h4" component="div" className={styles.title}>
                  Ciment
                </Typography>
                <div className={styles.goalContent}>
                  <div className={styles.goal}>
                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Objectif:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        100,000,000 FCFA
                      </Typography>
                    </div>

                    <LinearProgress variant="determinate" className={styles.progress} value={10} />

                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Atteint:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        100,000,000 FCFA
                      </Typography>
                    </div>
                  </div>
                </div>
              </CardContent>
              <CardActions>
                <Button variant="contained" size='large' fullWidth className='btn'>Faire un don</Button>
              </CardActions>
            </Card>
            <Card className={styles.needCard}>
              <CardMedia
                sx={{ height: 140 }}
                image="/rond-a-beton.jpg"
                title="green iguana"
              />
              <CardContent>
                <Typography gutterBottom variant="h4" component="div" className={styles.title}>
                  Botte de fer
                </Typography>
                <div className={styles.goalContent}>
                  <div className={styles.goal}>
                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Objectif:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        100,000,000 FCFA
                      </Typography>
                    </div>

                    <LinearProgress variant="determinate" className={styles.progress} value={10} />

                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Atteint:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        100,000,000 FCFA
                      </Typography>
                    </div>
                  </div>
                </div>
              </CardContent>
              <CardActions>
                <Button variant="contained" size='large' fullWidth className='btn'>Faire un don</Button>
              </CardActions>
            </Card>
            <Card className={styles.needCard}>
              <CardMedia
                sx={{ height: 140 }}
                image="/gravier.jpg"
                title="green iguana"
              />
              <CardContent>
                <Typography gutterBottom variant="h4" component="div" className={styles.title}>
                  Gravier
                </Typography>
                <div className={styles.goalContent}>
                  <div className={styles.goal}>
                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Objectif:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        10000 FCFA
                      </Typography>
                    </div>

                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Atteint:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        1000 FCFA
                      </Typography>
                    </div>
                  </div>
                  <LinearProgress variant="determinate" className={styles.progress} value={10} />
                </div>
              </CardContent>
              <CardActions>
                <Button variant="contained" size='large' fullWidth className='btn'>Faire un don</Button>
              </CardActions>
            </Card>
            <Card className={styles.needCard}>
              <CardMedia
                sx={{ height: 140 }}
                image="/gravier.jpg"
                title="green iguana"
              />
              <CardContent>
                <Typography gutterBottom variant="h4" component="div" className={styles.title}>
                  Gravier
                </Typography>
                <div className={styles.goalContent}>
                  <div className={styles.goal}>
                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Objectif:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        10000 FCFA
                      </Typography>
                    </div>

                    <div className={styles.item}>
                      <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                        Atteint:
                      </Typography>
                      <Typography gutterBottom className={styles.value}>
                        1000 FCFA
                      </Typography>
                    </div>
                  </div>
                  <LinearProgress variant="determinate" className={styles.progress} value={10} />
                </div>
              </CardContent>
              <CardActions>
                <Button variant="contained" size='large' fullWidth className='btn'>Faire un don</Button>
              </CardActions>
            </Card>
          </div>
        </section>

        <Modal
          open={false}
          // onClose={handleClose}
          aria-labelledby="modal-modal-title"
          aria-describedby="modal-modal-description"
          className='containerPaymentModal'
        >
          <Card className='paymentModal'>
            <CardMedia
              sx={{ height: 140 }}
              image="/about.jpg"
              title="green iguana"
            />
            <CardContent>
              <Typography gutterBottom variant="h4" component="div" className={styles.title}>
                Sable
              </Typography>
              <div className={styles.goalContent}>
                <div className={styles.goal}>
                  <div className={styles.item}>
                    <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                      Objectif:
                    </Typography>
                    <Typography gutterBottom className={styles.value}>
                      10000 FCFA
                    </Typography>
                  </div>

                  <div className={styles.item}>
                    <Typography gutterBottom variant="h6" component="div" className={styles.title}>
                      Atteint:
                    </Typography>
                    <Typography gutterBottom className={styles.value}>
                      1000 FCFA
                    </Typography>
                  </div>
                </div>
                <LinearProgress variant="determinate" className={styles.progress} value={10} />
              </div>
            </CardContent>
            <CardActions>
              <Button variant="contained" size='large' fullWidth className='btn'>Contactez-nous</Button>
            </CardActions>
          </Card>
        </Modal>
      </main>
    </>
  )
}